# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: hello@shyaamdeshmukh.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/readytoship"
url: "http://www.shyaamdeshmukh.com"
twitter_username: Shyaam
github_username:  shyaam
facebook_username:  shyaam.deshmukh

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
